language: ruby
cache: bundler
rvm:
- 2.1
before_script: bundle update
script: jekyll build && htmlproof ./_site
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer